# Generated by Django 4.0.1 on 2022-02-23 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100, unique=True)),
                ('age', models.IntegerField()),
                ('occupation', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('complaint', models.CharField(default='', max_length=100)),
                ('date_walk_in', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('check_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('payment', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('date_paid', models.DateField(blank=True)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.treatment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointed', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_treatment', to='api.treatment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointment', to='api.patient')),
            ],
        ),
    ]
