# Generated by Django 4.0.1 on 2022-03-17 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_processpayments_date_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_walk_in',
        ),
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
