# Generated by Django 4.0.1 on 2022-03-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_patient_first_name_alter_patient_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
