# Generated by Django 4.0.1 on 2022-03-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_patient_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(default='', max_length=11, unique=True),
        ),
    ]
