# Generated by Django 4.0.1 on 2022-03-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_patient_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processpayments',
            name='date_paid',
        ),
        migrations.AddField(
            model_name='processpayments',
            name='process_by',
            field=models.CharField(default='', max_length=100),
        ),
    ]
