# Generated by Django 4.0.1 on 2022-03-21 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_processpayments_date_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paid', models.DateField(blank=True)),
                ('check_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('process_by', models.CharField(default='', max_length=100)),
                ('process_payments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.processpayments')),
            ],
        ),
    ]
