# Generated by Django 4.0.1 on 2022-01-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraccountpasswordandemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountpasswordandemail',
            name='is_secretary',
            field=models.BooleanField(default=False),
        ),
    ]
