# Generated by Django 4.0.1 on 2022-03-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_useraccountpasswordandemail_is_secretary'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
